apiVersion: v1
kind: ReplicationController
metadata:
  name: strongbox
  namespace: kube-system
  # these labels can be applied automatically
  # from the labels in the pod template if not set
  labels:
    app: dataplayers
    tier: strongbox
spec:
  # this replicas value is default
  # modify it according to your case
  replicas: 1
  # selector can be applied automatically
  # from the labels in the pod template if not set
  # selector:
  #   app: guestbook
  #   tier: frontend
  template:
    metadata:
      labels:
        app: dataplayers
        tier: strongbox
    spec:
      containers:
      - name: data-players-strongbox
        image: dataplayers/strongbox
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 200m
            memory: 500Mi
        env:
        - name: version
          value: prod/1.0
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: data-players-strongbox-service
spec:
  selector:
    app: dataplayers
    tier: strongbox
  ports:
  - port: 80
    targetPort: 80
