apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dp-traefik-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.frontend.rule.type: PathPrefixStrip
##    ingress.kubernetes.io/rewrite-target : /
##    ingress.kubernetes.io/add-base-url: "true"

spec:
  rules:
  - host : semantic-bus.org
    http:
      paths:
      - path : /landing
        backend:
          serviceName: dp-wordpress
          servicePort: 80
